accessControl:
  enabled: false
server:
  firstRun: false
api:
  allowCrossOrigin: true
appearance: {}
feature:
  sdSupport: false
  waitForStartOnConnect: true
gcodeViewer:
  enabled: false
serial:
  port: /dev/ttyACM0
  baudrate: 250000
  autoconnect: true
  timeout:
    connection: 2
appearance:
  components:
    disabled:
      settings:
      - serial
      - printerprofiles
      - terminalfilters
      - server
      - section_features
      - features
      - webcam
      - api
      - folders
      - appearance
      - section_octoprint
      - plugin_ScreenSquish
      tab:
      - timelapse
    order:
      settings:
      - section_printer
      - plugin_automation_scripts
temperature:
  profiles:
  - bed: '50'
    extruder: '200'
    name: PLA
terminalFilters:
- name: Suppress M105 requests/responses
  regex: '(Send: M105)|(Recv: ok (B|T\d*):)'
webcam:
  stream: /webcam/?action=stream
  snapshot: http://127.0.0.1:8080/?action=snapshot
  ffmpeg: /usr/bin/avconv
plugins:
  _disabled:
  - cura
  cura:
    cura_engine: /usr/local/bin/cura_engine
  discovery:
    publicPort: 80
  softwareupdate:
    checks:
      octoprint:
        update_folder: /home/pi/OctoPrint
    octoprint_restart_command: sudo service octoprint restart
    environment_restart_command: sudo shutdown -r now
system:
  actions:
  - name: Shutdown
    command: sudo shutdown -h now
    action: shutdown
    confirm: You are about to shutdown the system.
    async: true
    ignore: true
  - name: Reboot
    command: sudo shutdown -r now
    action: reboot
    confirm: You are about to reboot the system
    async: true
    ignore: true
  - name: Restart Control Interface
    command: sudo service octoprint restart
    action: restart
    confirm: You are about to restart the Control Interface
    async: true
    ignore: true
  - action: update-automation-scripts
    command: cd /home/pi/.mecodescripts && git fetch && git reset --hard origin/master
    name: Update Automation Scripts
  - action: update-printer-ui
    command: cd /home/pi/printer_ui && git fetch && git reset --hard origin/master
    name: Update Printer UI
